### ISSUE TITLE
Conversion of JS to use relative paths

### ISSUE THREAD

**Issue by daniel-lewis-ab** [bmad4ever/comfyui_bmad_nodes#10]
Hi,

I'm going through a bunch of ComfyUI nodes and resolving some things here and there, as well as examining source.  A thing I noticed is that your imports are all absolute pathed.  I'd suggest adopting relative pathing so that comfyui doesn't have to be at / folder for a given project/company/website.

Most other nodes do follow that pattern already.  Otherwise, looking sharp.  Thanks for your help!

**Comment by bmad4ever** [comment]
Hi,

Thanks for reaching out.
At a glance, that seems trivial to change, but I won't be coding before 6th of April.

If you already fixed the problem on your end, I suggest that you send a pull request;  I should review it next weekend.

Best Regards

**Comment by daniel-lewis-ab** [comment]
https://github.com/bmad4ever/comfyui_bmad_nodes/pull/11

As mentioned, test before pulling

**Comment by bmad4ever** [comment]
merged #11 .
