### ISSUE TITLE
Question : Histogram

### ISSUE THREAD

**Issue by davask** [bmad4ever/comfyui_bmad_nodes#14]
Hi,

I'm part of a discord and we are looking to build a ComfyUI Node to manipulate Histogram like photoshop does it.

You seems to have quite some experience with this kind of things, could you help ?

here what we did so far :

https://github.com/gonzalu/ComfyUI_YFG_Comical/blob/main/image2histogram.py

![image](https://github.com/bmad4ever/comfyui_bmad_nodes/assets/482210/3973f7ca-76b3-4360-92f1-2abd9ec46801)

**Comment by bmad4ever** [comment]
Hi, 

That will be a bit complicated this week, but I might get some time on the weekend ( no guarantees ).

I am not familiar with photoshop though, only a bit of experience with GIMP.
**1 ) What is the particular node/functionality you need help with?
Can you provide a link or video showing the feature?**

I see that in your example the EqualizeHistogram node is used. It calls the openCV equalizeHist func over the greyscale image, which is perhaps not very useful to you. 
I can change the node behavior to work over an arbitrary channel (using an arbitrary color format), and then return a colored image.
**2) Would this be of use to you?**

Best Regards

**Comment by gonzalu** [comment]
Thank you so much. 

DISCLAIMER: I am not a dev so have little experience figuring things out. 

That being said, I am a good learner and can usually follow logic fairly well. 

The node is at:

https://github.com/gonzalu/ComfyUI_YFG_Comical

Specifically, the Histogram node. I have tried to get it to 

a: Colorize each of the resulting histogram graphs 
b: Output a single Channel per output (currently it dumps 3 on each) 
c: Transparency. When I output the resulting RGB Histogram, the goal is to overlay each of the individua lchannel histograms, in RED GREEN and BLUE but all blended together via filter like Screen or even just 50% opacity on the top two layers

Thank you. 

P.S. GIMP has come a long way so it is not far from Photoshop
P.P.S. This is NOT a Photoshop function solely but a very common one across ALL photo apps. Here are some samples below... 

![image](https://github.com/bmad4ever/comfyui_bmad_nodes/assets/32348862/87be0a5f-3cca-4905-bd0a-3a8f05f39480)


The overlay on this image shows how I have my Photoshop panels set up. 

What I wanted from the node is to export each of the channels as seen RED GREEN BLUE in their individual outputs and then the RGB output at the bottom of my node would look like the RGB one on the overlay. 

I did want at some point to overlay the results over my output main image as well as an output but it's not that important right now. 

If I knew how to wrangle the data inside the app, I can do the figuring out what to send to what output. 

My problem has been figuring out how to get MatPlot or PIL to do it :( 


THANK YOU SO MUCH for your advice and insight... much obliged

**Comment by gonzalu** [comment]
To further illustrate what my goal is...  the images depicted on the right from photoshop is what I would like to send to each of the RETURNS on my node :D 

It works now... it's just that I can't color them, and I can't get it to send ONLY ONE per output lol 

![image](https://github.com/bmad4ever/comfyui_bmad_nodes/assets/32348862/80f38e37-905b-44b1-9437-069df4e1d13f)

**Comment by gonzalu** [comment]
Currently what I think PIL is doing (or MatPlot) is doing a calculation on each of the channels for all the channels... 

Also, the whole Luminance only images vs RGB images is giving me a headache hahaha.

**Comment by bmad4ever** [comment]
I see you have made progress.
I will close the issue now.

Kind regards.

**Comment by gonzalu** [comment]
Thank you so much. I did make great progres... My nodes have been published and I used them every day. Hope others find them useful too.
