### ISSUE TITLE
Trying to find Denoise Ksampler node in bmad nodes????

### ISSUE THREAD

**Issue by Skettalee** [bmad4ever/comfyui_bmad_nodes#18]
I have been trying to follow a youtube video: https://www.youtube.com/watch?v=62sBGYC_z_o
Where Olivio Sarikas does something with segments and inpainting and there are nodes in his workflow that say its from the bmad padck called Denoise KSampler but I cant find that to save my life please someone help me from going mad to tell me whats wrong with me that i always try to find nodes that i visually see in a youtube video but tracking those actual nodes down and especially trying to ask questions from the person the creates these videos has been impossible. Even trying to use discord is impossible for me as the software is too cluttered with too many words, links, buttons and damn images every where that it triggers my adhd and i start having a panic attack. Im just trying to find a place where i can get this answers and im coming up short. Is there an actual Denoise Ksampler node that is suppose to be in the bmad pack and why would i not have it? I search with the type to search nodes when i double click in comfyui but nothing.............

**Comment by bmad4ever** [comment]
I don't recall any node named Denoise KSampler.
After watching the video, the node appears around 3:10, from comfyui-mixlab-nodes.

If you do not find the node, the title may have been manually changed, similar to the primitive-like nodes around the same timestamp. If not for the first argument, I would attempt to search for some node with "float", "interval", "range" or maybe "list" in the name.

Kind Regards

**Comment by Skettalee** [comment]
Thank you for your response. I will try to see if I can figure it out from what you have told me. I appreciate you!
