### ISSUE TITLE
Using tuples for `CATEGORY` is probably a bad idea?

### ISSUE THREAD

**Issue by Trung0246** [bmad4ever/comfyui_bmad_nodes#9]
https://github.com/bmad4ever/comfyui_bmad_nodes/blob/837fef4b310f3584e0bfbc9172256162e2b20c07/simple_utilities.py#L761

Usually this should be a string. Not sure about rationale behind this since some other extensions may expect `CATEGORY` to be string.

**Comment by bmad4ever** [comment]
Hello,

At first glance, it looks like some mindless copy-pasting was going around.
I will check this again tomorrow or Saturday.

Thank you for reaching out; these kinds of details can creep unnoticed quite easily.

Kind Regards
